# Generated by Django 2.0 on 2018-07-22 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kotha_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('message_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_by', to='kotha_app.Kotha_user')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_to', to='kotha_app.Kotha_user')),
            ],
        ),
        migrations.AddField(
            model_name='blocked_list',
            name='block_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='block_to', to='kotha_app.Kotha_user'),
        ),
        migrations.AddField(
            model_name='blocked_list',
            name='blocked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocked_by', to='kotha_app.Kotha_user'),
        ),
    ]
