# Generated by Django 2.0 on 2018-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotha_user',
            name='age',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
