# Generated by Django 2.0 on 2018-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotha_app', '0002_kotha_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logged_in_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usernames', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='kotha_user',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
