# Generated by Django 2.0 on 2018-07-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotha_app', '0003_auto_20180725_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logged_in_users',
            old_name='usernames',
            new_name='username',
        ),
    ]
