# Generated by Django 2.0 on 2018-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotha_app', '0006_auto_20180729_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotha_user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
